### ISSUE TITLE
Question about automated build

### ISSUE THREAD

**Issue by JosephLutz** [synctree/docker-mediawiki#8]
The Build Details on DockerHub shows that the image synctree/mediawiki was updated 2015-07-13 and 2015-07-14. I am not seeing the reason why this rebuild occurred. My closest guess is due to the update of php:5.6-apache base image five days ago.
I was able to use LDAP authentication in this image before this rebuild occured. I am trying to narrow down what all changed that could have caused the LDAP authentication to stop working.

**Comment by md5** [comment]
The automated build on Docker hub has a repository link to the `php` image as you guessed. That's the only reason a build would have been triggered, since there haven't been any updates to this repo in some time.

**Comment by JosephLutz** [comment]
I have found that the update of php:5.6-apache base image from 5.6.10 to 5.6.11 caused the LdapAuthentication extension to stop working. This is not a problem in synctree/docker-mediawiki.

**Comment by md5** [comment]
Cool. Thanks for following up.
