### ISSUE TITLE
Error response from daemon: Cannot set self as child

### ISSUE THREAD

**Issue by colonelchlorine** [synctree/docker-mediawiki#9]
When I run

```
docker run --name mywiki --link mywiki:mysql -p 8080:80 -d synctree/mediawiki
```

I get the following:

```
73b605ad92efbd1bea8575013a6965326df04bee07962863d5d3f92092e6f3c9
2015/09/21 17:42:11 Error response from daemon: Cannot set self as child
```

Any ideas? Here's my docker version info:
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.2.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.2.1
Git commit (server): fa7b24f

**Comment by md5** [comment]
You're trying to link a container (`mywiki`) to itself with your `--link` option. You want to `--link` to a separate DB container instead (e.g. `--link mywiki-mysql:mysql`).

**Comment by colonelchlorine** [comment]
Aha. I can create another mysql container. If I removed the link, does synctree/mediawiki have all that's required inside the container (i.e. mysql)? Sorry, not fully familiar with docker.

**Comment by md5** [comment]
​No. There isn't a database running inside the container. You need to link
one as specified in the README.

**Comment by colonelchlorine** [comment]
ok thanks
